name: Deploy to Cloudflare workers

on:
  push:
    branches:
      - main
    paths:
      - "sb-month/**"
      - ".github/workflows/sb-month-*.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: ./sb-month
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn install
      - name: test
        run: yarn test-no-watch
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "sb-month"
