name: Deploy to Cloudflare workers

on:
  push:
    branches:
      - main
    paths:
      - "sb-month/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "sb-month"
